### ISSUE TITLE
a little bug in the data prepare process

### ISSUE THREAD

**Issue by yuanjun1991** [Li-Ming-Fan/Task-Independent-ModelWrapper#1]
def standardize_list_seqs(x, min_seq_len=5, max_seq_len=100):
    """ x: list of seqs
    """
    x_padded = []
    x_len = []
    padded_len = max(min_seq_len, max([len(item) for item in x]))
    padded_len = min(max_seq_len, padded_len)
    for item in x:
        l = len(item)
        d = padded_len - l
        item_n = item.copy()
        if d > 0:
            item_n.extend([0] * d)  # pad_id, 0
        elif d < 0:
            item_n = item_n[0:max_seq_len]
            l = max_seq_len
        #
        x_padded.append(item_n)
        x_len.append(l)
        
    return x_padded, x_len

i think  this line :item_n = item_n[0:max_seq_len] should be: item_n = item_n[0:padded_len],
do you think so?

**Comment by Li-Ming-Fan** [comment]
@yuanjun1991

Yes, you are right. Thanks. I have rectified the codes there.
